name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependecies
        run: |
          pip install dvc dvc-gdrive
          pip install -r requirements_test.txt
      - name:
        run: |
          dvc pull model/model.pkl -r model-track
          pytest .
